In [2]:
import numpy as np
import pandas as pd
import pickle

# Simple Datasets for Base System

In [ ]:
DIR = 'C:\\Users\\jesse\\Desktop\\Honors Project\\'
int_interested = pd.read_parquet(DIR + 'ya_interactions_interested.parquet')
int_read = pd.read_parquet(DIR + 'ya_interactions_read.parquet')

DIR = 'C:\\Users\\jesse\\Desktop\\Honors Project\\goodreads_data\\raw\\'
books = pd.read_parquet(DIR+'ya_books_clean.parquet')

In [ ]:
books_simple = books[['book_id','title']]
books_simple.to_csv(DIR+'books_simple.csv',index=False)

In [ ]:
int_read = int_read[int_read['rating'] != 0]

In [ ]:
simple_ratings = int_read[['user_id', 'book_id', 'rating']]
simple_ratings.to_csv(DIR+'simple_ratings.csv', index=False)

## User interactions

In [7]:
DIR= 'C:\\Users\\jesse\\Desktop\\Honors Project\\'
with open(DIR + 'reviews_Lex_analyzed.pkl', 'rb') as f:
    reviews = pickle.load(f)
reviews = reviews.drop(columns=['review_text_lemmatized', 'bigrams','trigrams','tokenized'])
reviews = reviews.reset_index(drop=True)

In [8]:
emotions = pd.DataFrame.from_records(reviews['lex_emotions'])

emotions = emotions.fillna(0)

reviews = pd.concat([reviews, emotions], axis=1)

reviews = reviews.drop(columns=['lex_emotions'])

In [ ]:
all_int = pd.concat([int_interested, int_read], axis=0)
all_int = all_int.reset_index(drop=True)

In [9]:
mapping = all_int.set_index('review_id')['user_id'].to_dict()

reviews['user_id'] = reviews['review_id'].map(mapping)

In [60]:
reviews

,book_id,review_id,rating,review_text,n_votes,n_comments,all_caps,compassionate,nostalgic,sad,dissapointed,confused,inspired,excited,joyful,anxious,sensual,offended,optimistic,uncomfortable,user_id
0,2767052,248c011811e945eca861b5c31a549291,5,I cracked and finally picked this up. Very enj...,24,25,0,6.0,3.0,3.0,3.0,3.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,8842281e1d1347389f2ab93d60773d4d
1,23302416,84c0936a0f9868f38e75d2f9a5cb761e,5,I read this book because my fifth grade son wa...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,7504b2aee1ecb5b2872d3da381c6c91e
2,18053080,785c8db878f4009da9741dea51f641da,4,Though the book started out slow and only star...,0,0,0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,f8a89075dc6de14857561522e729f82c
3,17383543,34dc3c45d07e82718b05e73167259aef,2,"*Update - 10/27/13* - After some sleep, I thin...",0,0,0,1.0,3.0,8.0,4.0,3.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,f8a89075dc6de14857561522e729f82c
4,16651458,d8d6b590780256fef7ae4a9550fe3e0d,5,"This is a moving, heartbreaking, view into a l...",0,0,0,0.0,2.0,1.0,0.0,0.0,3.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,f8a89075dc6de14857561522e729f82c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2140845,6137154,1f6fc20b8187e8f36e12daf947b13e66,5,A really amazing book! It goes great with Grac...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,a13e16a58266ffa4a0851c417c4cda8f
2140846,10193062,fc86ebe129a7f14a09c0221c92f52f79,3,This book is better then the first. It has it'...,0,0,0,1.0,2.0,4.0,3.0,0.0,0.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,fc5aea6994fc754daefa27cbea10ac79
2140847,6186357,15d0f64aa991f270c490e1a4d5b4011b,2,I think this may have come from having expecta...,0,0,0,1.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,fc5aea6994fc754daefa27cbea10ac79
2140848,14740456,b048505c5b1e9ab8695afa3edce1b5d9,4,I generally liked the book. It had some parts ...,0,0,0,1.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,fc5aea6994fc754daefa27cbea10ac79
2140849,7137327,9e332909706db667f28cd16567bbea07,3,To be honest I would probably rank it some whe...,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,fc5aea6994fc754daefa27cbea10ac79

In [61]:
#drop review_id and review_text
reviews = reviews.drop(columns=['review_id', 'review_text'])

,book_id,rating,n_votes,n_comments,all_caps,compassionate,nostalgic,sad,dissapointed,confused,inspired,excited,joyful,anxious,sensual,offended,optimistic,uncomfortable,user_id
0,2767052,5,24,25,0,6.0,3.0,3.0,3.0,3.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,8842281e1d1347389f2ab93d60773d4d
1,23302416,5,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,7504b2aee1ecb5b2872d3da381c6c91e
2,18053080,4,0,0,0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,f8a89075dc6de14857561522e729f82c
3,17383543,2,0,0,0,1.0,3.0,8.0,4.0,3.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,f8a89075dc6de14857561522e729f82c
4,16651458,5,0,0,0,0.0,2.0,1.0,0.0,0.0,3.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,f8a89075dc6de14857561522e729f82c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2140845,6137154,5,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,a13e16a58266ffa4a0851c417c4cda8f
2140846,10193062,3,0,0,0,1.0,2.0,4.0,3.0,0.0,0.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,fc5aea6994fc754daefa27cbea10ac79
2140847,6186357,2,0,0,0,1.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,fc5aea6994fc754daefa27cbea10ac79
2140848,14740456,4,0,0,0,1.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,fc5aea6994fc754daefa27cbea10ac79
2140849,7137327,3,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,fc5aea6994fc754daefa27cbea10ac79

In [62]:
reviews.to_csv(DIR+'reviews_emotions.csv', index=False)

## User Data

In [10]:
# Group by 'user_id' and aggregate 'book_id' into lists
user_read = int_read.groupby('user_id')['book_id'].apply(list).reset_index()
user_read = user_read.rename(columns={'book_id':'read'})
user_reviewed = reviews.groupby('user_id')['book_id'].apply(list).reset_index()
user_reviewed = user_reviewed.rename(columns={'book_id':'reviewed'})
user_interested = int_interested.groupby('user_id')['book_id'].apply(list).reset_index()
user_interested = user_interested.rename(columns={'book_id':'interested'})
user_data = pd.merge(user_read, user_reviewed, on='user_id', how='outer')
user_data = pd.merge(user_data, user_interested, on='user_id', how='outer')

In [11]:
user_data['read_len'] = user_data['read'].apply(lambda x: len(x) if isinstance(x, list) else np.nan)
user_data['reviewed_len'] = user_data['reviewed'].apply(lambda x: len(x) if isinstance(x, list) else np.nan)

In [12]:
def get_emotions(user_id, rating):
    if isinstance(user_id, list):
        emotions = reviews[(reviews['user_id'].isin(user_id)) & (reviews['rating'] >= rating)][['anger', 'anticipation', 'disgust', 'fear', 'joy', 'sadness', 'surprise', 'trust']]
        emotions = emotions.mean()
        return emotions
    else:
        return np.nan

In [13]:
user_review_data=reviews.groupby(['user_id','rating']).agg({ 'compassionate':'sum', 'nostalgic':'sum', 'sad':'sum', 'dissapointed':'sum', 'confused':'sum', 'inspired':'sum', 'joyful':'sum','excited':'sum', 'anxious':'sum','sensual':'sum','offended':'sum','optimistic':'sum', 'uncomfortable':'sum'}).reset_index()

user_review_data_2 = reviews.groupby(['user_id','rating']).agg({
    'compassionate': lambda x: (x != 0).sum(),
    'nostalgic': lambda x: (x != 0).sum(),
    'sad': lambda x: (x != 0).sum(),
    'dissapointed': lambda x: (x != 0).sum(),
    'confused': lambda x: (x != 0).sum(),
    'inspired': lambda x: (x != 0).sum(),
    'joyful': lambda x: (x != 0).sum(),
    'excited': lambda x: (x != 0).sum(),
    'anxious': lambda x: (x != 0).sum(),
    'sensual': lambda x: (x != 0).sum(),
    'offended': lambda x: (x != 0).sum(),
    'optimistic': lambda x: (x != 0).sum(),
    'uncomfortable': lambda x: (x != 0).sum(),
    'book_id': 'count'
}).reset_index()

user_review_data_2.columns = ['count_'+str(col) if col != 'user_id' and col != 'rating' else col for col in user_review_data_2.columns]

user_review_data = pd.merge(user_review_data, user_review_data_2, on=['user_id','rating'], how='outer')

In [40]:
user_enjoyed = user_review_data[user_review_data['rating'] >= 4].drop('rating', axis=1).groupby('user_id').sum()
user_enjoyed = user_enjoyed[['count_compassionate', 'count_nostalgic',
       'count_sad', 'count_dissapointed', 'count_confused', 'count_inspired',
       'count_joyful', 'count_excited', 'count_anxious', 'count_sensual',
       'count_offended', 'count_optimistic', 'count_uncomfortable',
       'count_book_id']]
for col in user_enjoyed.columns:
    if col != 'count_book_id':
        new_col_name = col.replace('count_', '') + '_p'
        user_enjoyed[new_col_name] = user_enjoyed[col] / user_enjoyed['count_book_id']
user_enjoyed = user_enjoyed[['count_book_id', 'compassionate_p', 'nostalgic_p', 'sad_p',
       'dissapointed_p', 'confused_p', 'inspired_p', 'joyful_p', 'excited_p',
       'anxious_p', 'sensual_p', 'offended_p', 'optimistic_p',
       'uncomfortable_p']]
user_enjoyed.reset_index(inplace=True)

In [51]:
user_enjoyed

,user_id,count_book_id,compassionate_p,nostalgic_p,sad_p,dissapointed_p,confused_p,inspired_p,joyful_p,excited_p,anxious_p,sensual_p,offended_p,optimistic_p,uncomfortable_p
0,00000377eea48021d3002730d56aca9a,1,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
1,00009e46d18f223a82b22da38586b605,3,0.000000,0.000000,0.333333,0.333333,0.000000,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0000c3d51aa099745e93a4e99c4856c8,27,0.407407,0.333333,0.555556,0.444444,0.222222,0.185185,0.111111,0.222222,0.259259,0.333333,0.037037,0.037037,0.000000
3,000157a6f8331e9c9a21252e1fee91d1,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
4,00017868aee19101bca0817fe915c881,1,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166431,ffff483c0ce66e6475445eab566bb48f,4,0.750000,0.750000,1.000000,0.750000,1.000000,0.750000,0.500000,0.750000,0.750000,0.750000,0.500000,0.250000,0.000000
166432,ffff601c0ffa34bd5ffbbf2caee30644,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
166433,ffff7cafdaf5196383cb2efca08fb6fe,146,0.397260,0.410959,0.417808,0.390411,0.301370,0.232877,0.157534,0.273973,0.157534,0.212329,0.136986,0.061644,0.061644
166434,ffff943e2e329be4f410d874aaa3ae7f,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
166435,fffff8a718843c0e11dfd93fb41c1297,5,0.400000,0.400000,0.400000,0.400000,0.200000,0.000000,0.200000,0.000000,0.200000,0.400000,0.200000,0.000000,0.000000

In [47]:
user_disliked = user_review_data[user_review_data['rating'] <= 2].drop('rating', axis=1).groupby('user_id').sum()
user_disliked = user_disliked[['count_compassionate', 'count_nostalgic',
       'count_sad', 'count_dissapointed', 'count_confused', 'count_inspired',
       'count_joyful', 'count_excited', 'count_anxious', 'count_sensual',
       'count_offended', 'count_optimistic', 'count_uncomfortable',
       'count_book_id']]
for col in user_disliked.columns:
    if col != 'count_book_id':
        new_col_name = col.replace('count_', '') + '_p'
        user_disliked[new_col_name] = user_disliked[col] / user_disliked['count_book_id']
user_disliked = user_disliked[['count_book_id', 'compassionate_p', 'nostalgic_p', 'sad_p',
       'dissapointed_p', 'confused_p', 'inspired_p', 'joyful_p', 'excited_p',
       'anxious_p', 'sensual_p', 'offended_p', 'optimistic_p',
       'uncomfortable_p']]
user_disliked.reset_index(inplace=True)

In [53]:
for col in user_enjoyed.columns:
    if col != 'user_id':
        user_enjoyed['liked_'+ col] = user_enjoyed[col]
        user_enjoyed.drop(col, axis=1, inplace=True)

,user_id,liked_count_book_id,liked_compassionate_p,liked_nostalgic_p,liked_sad_p,liked_dissapointed_p,liked_confused_p,liked_inspired_p,liked_joyful_p,liked_excited_p,liked_anxious_p,liked_sensual_p,liked_offended_p,liked_optimistic_p,liked_uncomfortable_p
0,00000377eea48021d3002730d56aca9a,1,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
1,00009e46d18f223a82b22da38586b605,3,0.000000,0.000000,0.333333,0.333333,0.000000,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0000c3d51aa099745e93a4e99c4856c8,27,0.407407,0.333333,0.555556,0.444444,0.222222,0.185185,0.111111,0.222222,0.259259,0.333333,0.037037,0.037037,0.000000
3,000157a6f8331e9c9a21252e1fee91d1,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
4,00017868aee19101bca0817fe915c881,1,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166431,ffff483c0ce66e6475445eab566bb48f,4,0.750000,0.750000,1.000000,0.750000,1.000000,0.750000,0.500000,0.750000,0.750000,0.750000,0.500000,0.250000,0.000000
166432,ffff601c0ffa34bd5ffbbf2caee30644,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
166433,ffff7cafdaf5196383cb2efca08fb6fe,146,0.397260,0.410959,0.417808,0.390411,0.301370,0.232877,0.157534,0.273973,0.157534,0.212329,0.136986,0.061644,0.061644
166434,ffff943e2e329be4f410d874aaa3ae7f,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
166435,fffff8a718843c0e11dfd93fb41c1297,5,0.400000,0.400000,0.400000,0.400000,0.200000,0.000000,0.200000,0.000000,0.200000,0.400000,0.200000,0.000000,0.000000

In [54]:
for col in user_disliked.columns:
    if col != 'user_id':
        user_disliked['disliked_'+ col] = user_disliked[col]
        user_disliked.drop(col, axis=1, inplace=True)

In [57]:
#merge user_enjoyed with user_disliked on user_id
user_emotions = pd.merge(user_enjoyed, user_disliked, on='user_id', how='outer')
user_emotions = user_emotions.fillna(0)

,user_id,liked_count_book_id,liked_compassionate_p,liked_nostalgic_p,liked_sad_p,liked_dissapointed_p,liked_confused_p,liked_inspired_p,liked_joyful_p,liked_excited_p,liked_anxious_p,liked_sensual_p,liked_offended_p,liked_optimistic_p,liked_uncomfortable_p,disliked_count_book_id,disliked_compassionate_p,disliked_nostalgic_p,disliked_sad_p,disliked_dissapointed_p,disliked_confused_p,disliked_inspired_p,disliked_joyful_p,disliked_excited_p,disliked_anxious_p,disliked_sensual_p,disliked_offended_p,disliked_optimistic_p,disliked_uncomfortable_p
0,00000377eea48021d3002730d56aca9a,1.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
1,00009e46d18f223a82b22da38586b605,3.0,0.000000,0.000000,0.333333,0.333333,0.000000,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.0,0.000000,0.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
2,0000c3d51aa099745e93a4e99c4856c8,27.0,0.407407,0.333333,0.555556,0.444444,0.222222,0.185185,0.111111,0.222222,0.259259,0.333333,0.037037,0.037037,0.000000,4.0,0.250000,0.250000,0.750000,0.500000,0.500000,0.000000,0.000000,0.000000,0.500000,0.250000,0.000000,0.0,0.000000
3,0001085188e302fc6b2568de45a5f56b,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.0,0.000000
4,000157a6f8331e9c9a21252e1fee91d1,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179975,ffff483c0ce66e6475445eab566bb48f,4.0,0.750000,0.750000,1.000000,0.750000,1.000000,0.750000,0.500000,0.750000,0.750000,0.750000,0.500000,0.250000,0.000000,3.0,0.666667,0.666667,1.000000,0.666667,0.000000,0.333333,0.333333,0.333333,0.666667,0.333333,0.000000,0.0,0.000000
179976,ffff601c0ffa34bd5ffbbf2caee30644,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
179977,ffff7cafdaf5196383cb2efca08fb6fe,146.0,0.397260,0.410959,0.417808,0.390411,0.301370,0.232877,0.157534,0.273973,0.157534,0.212329,0.136986,0.061644,0.061644,47.0,0.425532,0.446809,0.404255,0.340426,0.319149,0.148936,0.148936,0.234043,0.170213,0.127660,0.085106,0.0,0.085106
179978,ffff943e2e329be4f410d874aaa3ae7f,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
179979,fffff8a718843c0e11dfd93fb41c1297,5.0,0.400000,0.400000,0.400000,0.400000,0.200000,0.000000,0.200000,0.000000,0.200000,0.400000,0.200000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000

In [58]:
user_emotions.to_csv(DIR+'user_preferences.csv', index=False)

## Book data

In [25]:
book_data = reviews.groupby('book_id').agg({'rating':'mean', 'compassionate':'mean', 'nostalgic':'mean', 'sad':'mean', 'dissapointed':'mean', 'confused':'mean', 'inspired':'mean', 'joyful':'mean','excited':'mean', 'anxious':'mean','sensual':'mean','offended':'mean','optimistic':'mean', 'uncomfortable':'mean','user_id':'count'}).reset_index()
book_data = book_data.rename(columns={'review_id':'review_count'})

In [59]:
book_data = pd.merge(book_data, books_simple, on='book_id', how='left')
book_data.to_csv(DIR+'books_emotions.csv', index=False)